[2024-07-12 14:30:53,911: INFO: main: Welcome to our custom logging]
[2024-07-12 16:54:58,132: INFO: main: Welcome to our custom logging]
[2024-07-13 20:30:19,512: INFO: main: Welcome to our custom logging]
[2024-07-13 20:50:07,394: ERROR: 3458077506: An error occurred: [Errno 2] No such file or directory: 'config/config.yaml']
[2024-07-13 20:50:51,561: ERROR: 1978635381: An error occurred: [Errno 2] No such file or directory: 'config/config.yaml']
[2024-07-13 20:51:38,579: ERROR: 1134838982: An error occurred: [Errno 2] No such file or directory: 'config/config.yaml']
[2024-07-13 20:52:20,677: ERROR: 1978635381: An error occurred: [Errno 2] No such file or directory: 'config/config.yaml']
[2024-07-13 20:55:11,486: ERROR: 1278220572: An error occurred: [Errno 2] No such file or directory: 'config/config.yaml']
[2024-07-13 23:52:59,024: INFO: main: Welcome to our custom logging]
[2024-07-14 01:20:03,158: INFO: main: Welcome to our custom logging]
[2024-07-14 02:09:30,699: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-14 02:09:30,700: INFO: common: yaml file: /Users/hymaroshinigompa/Downloads/Data_Science_End_To_End_with_ML/config/config.yaml loaded successfully]
[2024-07-14 02:09:30,701: INFO: common: yaml file: /Users/hymaroshinigompa/Downloads/Data_Science_End_To_End_with_ML/params.yaml loaded successfully]
[2024-07-14 02:09:30,701: INFO: common: yaml file: /Users/hymaroshinigompa/Downloads/Data_Science_End_To_End_with_ML/schema.yaml loaded successfully]
[2024-07-14 02:09:30,701: INFO: common: created directory at: artifacts]
[2024-07-14 02:09:30,701: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 02:09:30,701: INFO: data_ingestion: File already exists of size: ~ 25 KB]
[2024-07-14 02:09:30,703: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
